import './globals.css'
export const metadata = {
  title: 'Video-Stream',
  description: 'Generated by MeStrange007',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
